platform :ios, ‘8.0’
use_frameworks!
target ”ProjectB” do
pod 'BaiduMapKit', '~> 3.0.0'
pod 'UMengSocialCOM', '~> 5.2.1'

post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = "armv7s armv7"
    end
  end
end
end